### ISSUE TITLE
[BUG] (0 , se.createPackageJson) is not a function on "build-gateway" executor

### ISSUE THREAD

**Issue by mnlbox** [domjtalbot/nx-mesh#175]
Hi,

I'm trying to use the `build-gateway` executor. It always generates all the mesh build files successfully but in the end, I'm getting an error like this:
```
...
💡 🕸️  Mesh Generating artifacts
💡 🕸️  Mesh Generating index file in TypeScript
💡 🕸️  Mesh Writing index.ts for ESM to the disk.
💡 🕸️  Mesh Writing index.ts for CJS to the disk.
💡 🕸️  Mesh Cleanup
💡 🕸️  Mesh Done! => /workspaces/my-project/graph/my-project/.mesh

Creating package.json...

 >  NX   (0 , se.createPackageJson) is not a function


TypeError: (0 , se.createPackageJson) is not a function
    at Qn (/workspaces/my-project/node_modules/.pnpm/nx-mesh@4.0.0_@graphql-mesh+cli@0.82.35_@types+node@20.2.3_cypress@12.2.0_eslint@8.15.0_graph_m5iwccy7kfnbcedxjgauqqaxsa/node_modules/nx-mesh/src/executors/build-gateway/build-gateway.js:11:21091)
    at Wi (/workspaces/my-project/node_modules/.pnpm/nx-mesh@4.0.0_@graphql-mesh+cli@0.82.35_@types+node@20.2.3_cypress@12.2.0_eslmy-projectint@8.15.0_graph_m5iwccy7kfnbcedxjgauqqaxsa/node_modules/nx-mesh/src/executors/build-gateway/build-gateway.js:11:22798)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target build for project my-project failed

   Failed tasks:
   
   - my-project:build
```

And this is my build config in the `project.json` file:
```
"build": {
      "executor": "nx-mesh:build-gateway",
      "options": {
        "dir": "graph/my-project",
        "outputPath": "dist/graph/my-project"
      }
    },
```

It seems it's related to this part: https://github.com/domjtalbot/nx-mesh/blob/397cc741550cc552c6b24cc71aceed60093a1339/packages/nx-mesh/src/executors/build-gateway/build-gateway.ts#L47-L53

**Comment by mnlbox** [comment]
@domjtalbot Any idea about this issue?

**Comment by mnlbox** [comment]
@domjtalbot Are you still maintaining this repo?
